### PR TITLE
Implement event handler for AP connections

### PR DESCRIPTION
**Pull request by sebromero**
Tries to solve https://github.com/arduino/ArduinoCore-mbed/issues/78
```
if(event_header->event_type == 8){ //8 = connect
    WiFi._currentNetworkStatus = WL_AP_CONNECTED;
    return nullptr;
}

if(event_header->event_type == 12){ //12 = disconnect
    WiFi._currentNetworkStatus = WL_AP_LISTENING;
    return nullptr;
} 
```
@facchinm I couldn't figure out where those events for connect/disconnect are defined so I went with the raw values. Any hints?

### CODE REVIEW

**Comment by facchinm** [comment]
@sbhklr they can be retrieved from https://github.com/arduino/ArduinoCore-mbed/blob/master/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_PORTENTA_H7/COMPONENT_WHD/inc/whd_events.h#L42 .
As always, outstanding stuff! My only concern is that we are overriding default handler ([whd_default_handle_softap_events](https://github.com/arduino/mbed-os/blob/portenta-mbed-6.2.0/features/netsocket/emac-drivers/TARGET_STM/COMPONENT_WHD/interface/WhdSoftAPInterface.cpp#L37)) which takes care of sleeping... Shouldn't be a huge problem, we can probably deal with it later.

**Comment by sbhklr** [comment]
There doesn't seem to be a way to call the default handler beforehand. The function is private and there is no API for retrieving any registered event handler (couldn't find one) which could be used to anonymously call the default handler.
As the handler is just a few lines of code I copied into the `beginAP` function. Not so elegant but probably better than not dealing with the sleep events.

**Comment by facchinm** [comment]
@sbhklr copying the content of the default handler is fine, but since the function grew significantly I'd replace the lambda with a proper function pointer and extract it. What do you think?

**Comment by sbhklr** [comment]
@facchinm Fair enough, done.

**Comment by rchard-84** [comment]
I've run into this issue as well trying to move code from an UNO over to an H7.  When, very roughly, might this fix show up in a release.  Thanks for finding and fixing the issue.

**Comment by sebromero** [comment]
I think we're ready to merge this one.
@facchinm any time frame for the next core release?

**Comment by sebromero** [comment]
@rchard-84 Have you tested this PR? It works on my end, but always good to have more testers :-)

**Comment by facchinm** [comment]
> I think we're ready to merge this one.
> @facchinm any time frame for the next core release?

Ok for merging :slightly_smiling_face: Next release is due in a week more or less (after https://github.com/ARMmbed/mbed-os/pull/13826 gets merged)

**Comment by rchard-84** [comment]
I did not test the PR.  I lack the knowhow to go from your fix to a
compiled library that I can test on the portenta. Is there a walk through
someplace?  I'd be happy to try stuff out.

**Comment by sebromero** [comment]
@rchard-84 Basically you can check out this repository and put it in your sketchbook. Then you can select that version of the core from the menu in the IDE.
image

There might be some documentation on that. @per1234 if anyone, then you'll know it :-) Any hints?

**Comment by per1234** [comment]
As for the technique of using a copy of the core in the sketchbook for development/beta testing, there is an interesting discussion about it here:
https://github.com/arduino/Arduino/issues/9237

As for official documentation of the manual core installation process, there isn't any that I'm aware of beyond a quick mention in the Arduino Platform Specification (the preferred term for this is "platform"):
https://arduino.github.io/arduino-cli/latest/platform-specification/
>Platforms add support for new boards to the Arduino development software. They are installable either via Boards Manager or manual installation to the hardware folder of Arduino's sketchbook folder (AKA "user directory").

I would expect to find manual platform installation documented here: https://www.arduino.cc/en/Guide/Cores, but it only talks about Boards Manager installation.

**Comment by sebromero** [comment]
Thanks @per1234 ! I've asked content to add documentation to that page.

**Pull request merged**
