### PR TITLE
WiFi UDP & Multicast Functionality

### PR DESCRIPTION
**Pull request by sbhklr**
This PR implements some missing functions for WiFiUDP functionality. Previously it didn't compile because not all virtual functions were implemented. Some testing still need to be done.

### CODE REVIEW

**Comment by jwestmoreland** [comment]
I built with this - the wifi-udp branch - it apparently doesn't work - or maybe it doesn't work with multicast (yet) since my sketch is using multicast.  Note, if I use this branch, my sketch will reset every few minutes or so.  If I just include the WiFiUDP files that are included with the 1.2.1 version in this repo - the sketch doesn't reset but still no UDP via multicast.

Just an FYI. 

I'm not sure the debugger works either with the portenta_m7 yet - but I will look into the configs on that to see if there is one yet that supports the portenta.

Regards,
John W.

**Comment by sbhklr** [comment]
@facchinm Looks like we can merge this and close https://github.com/arduino/ArduinoCore-mbed/issues/15.

**Comment by jwestmoreland** [comment]
Sebastian,

Maybe change title to:  Wifi UDP & Multicast Functionality ?

Thanks,
John

**Comment by jwestmoreland** [comment]
Thanks Martino and Sebastian!

**Pull request merged**
