### PR TITLE
Update wiring_analog.cpp

### PR DESCRIPTION
**Pull request by alessandromrc**
Fixes a warning about comparing an integer to an unsigned integer

### CODE REVIEW

**Comment by facchinm** [comment]
Merged, thanks for your contribution!

**Comment by alessandromrc** [comment]
@facchinm I wanted to ask you if there's a possibility to avoid the Nicla Voice from always failing the test as it can mislead people when they see a board failing to compile

**Comment by facchinm** [comment]
Sure, I'm trying to understand which revision of arduino-audio-tools library introduced the regression (and pin to a previous version)

**Comment by facchinm** [comment]
Should be fixed by https://github.com/arduino/ArduinoCore-mbed/pull/668

**Pull request merged**
