### PR TITLE
Fix buffer sync issue in camera raw bytes example

### PR DESCRIPTION
**Pull request by sebromero**
Adds a very basic synchronization to the Arduino and Processing sketch to make sure the buffer doesn't get out of sync.
Here is the before / after comparison:

Before

After

### CODE REVIEW

**Comment by sebromero** [comment]
@iabdalkader Wdyt?

**Comment by iabdalkader** [comment]
You might want to add a timeout in the pde.

**Comment by sebromero** [comment]
> You might want to add a timeout in the pde.

@iabdalkader Can you elaborate? Timeout for what condition?

**Comment by iabdalkader** [comment]
@sebromero If the sketch misses even a single byte, the cam and the sketch will deadlock. Adding a 1 second ? timeout in the pde may allow it to recover from that without restarting the sketch. Just a suggestion but otherwise it looks good.

**Comment by sebromero** [comment]
@iabdalkader Makes sense. Added it 👍

**Review by facchinm — APPROVED** [review]

**Comment by gargoyle777** [comment]
i'm still having the exact same problem. i'm using the last released exemple by the way.

**Pull request merged**
