### PR TITLE
Moving SDRAM.begin() on Arduino_H7_Video - Artifacts Issue Fix

### PR DESCRIPTION
**Pull request by Jorgetrujilloroman**
This PR fixes issues like the reported [here](https://forum.arduino.cc/t/giga-display-shows-garbage-during-boot/1324050)

### CODE REVIEW

**Review by leonardocavagnis — CHANGES_REQUESTED** [review]
Please @Jorgetrujilloroman  apply this fix only on GIGA target 

```
#if defined(ARDUINO_GIGA) 
/* Configure SDRAM */
SDRAM.begin(dsi_getFramebufferEnd()); // Moving this line from line 156 to here solves the artifacts issue
#endif

...

#if !defined(ARDUINO_GIGA)
/* Configure SDRAM */
SDRAM.begin(dsi_getFramebufferEnd()); //FIXME: SDRAM init after video controller init can cause display glitch at start-up
#endif
```

**Comment by Jorgetrujilloroman** [comment]
> Please @Jorgetrujilloroman apply this fix only on GIGA target
> 
> ```
> #if defined(ARDUINO_GIGA) 
> /* Configure SDRAM */
> SDRAM.begin(dsi_getFramebufferEnd()); // Moving this line from line 156 to here solves the artifacts issue
> #endif
> 
> ...
> 
> #if !defined(ARDUINO_GIGA)
> /* Configure SDRAM */
> SDRAM.begin(dsi_getFramebufferEnd()); //FIXME: SDRAM init after video controller init can cause display glitch at start-up
> #endif
> ```

Done

**Comment by Jorgetrujilloroman** [comment]
@leonardocavagnis Done

**Review by leonardocavagnis — APPROVED** [review]

**Comment by leonardocavagnis** [comment]
@Jorgetrujilloroman Thanks!

**Pull request merged**
