### PR TITLE
Improve readme and add flag to turn debug info ON for libmbed

### PR DESCRIPTION
**Pull request by facchinm**

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]

**Comment by aentinger** [comment]
Looks to me like @per1234 already had a field day. I'll wait with my review until his suggestions have been resolved.

One thing I can say already is that if the intention is to provide information on how to create a debuggable build the text would need to be restructured a bit, like having a headline: "How to enable debugging for ArduinoCore-mbed based boards". I felt that although I personally know what to look for it was not that easy for me to extract that information.

**Review by per1234 — APPROVED** [review]
All good now from a nitpick standpoint. I don't have time now to evaluate in detail it from a technical standpoint, but I think this is a very nice enhancement over the previous documentation and script.

Thanks Martino!

**Comment by aentinger** [comment]
That's my take on improving the issue I mentioned above. What do you guys think?

**Comment by per1234** [comment]
Looks good to me.

**Comment by facchinm** [comment]
@aentinger thanks for the patch, it was much needed! I pushed another commit to explain how to change the project config file, hope it's clear enough

**Review by manchoz — COMMENTED** [review]
LGTM, too

**Pull request merged**
