### PR TITLE
WiFi: offload firmware to external QSPI

### PR DESCRIPTION
**Pull request by facchinm**
Based on https://github.com/arduino/mbed-os/pull/new/portenta_h7_wifi_on_qspi

If this patch gets merged, the WiFi on all boards will stop working until `PortentaWiFiFirmwareUpdater.ino` gets executed once.

Using the filesystem method, however, we could solve #25 very easily.

@sbhklr

### CODE REVIEW

**Comment by sbhklr** [comment]
@facchinm If I understand correctly, this is to free up flash memory. Sounds good, we just need to include that in the getting startet tutorial. Can we ship the new boards with the WiFi firmware pre-flashed?

**Comment by facchinm** [comment]
@sbhklr we can but it's not something that easily survives experimentation (if we load micropython, for example, the qspi flash gets  reformatted), so I'd prefer not to factory flash it.
About the advantages there are both flash occupation and download speed, so it's really important to have something like this (maybe in a different partition?)

**Comment by jwestmoreland** [comment]
Just wondering,

Where is:  PortentaWiFiFirmwareUpdater.ino ?

I've noticed the builds taking up more space than expected as well - glad to see you guys are on it.

**Comment by jwestmoreland** [comment]
FYI: Two typos in WiFi.cpp - lines 289 and 298 - missing ';' at end of each line.  (JIC)

**Comment by sbhklr** [comment]
Thanks John, we'll fix it!

**Comment by jwestmoreland** [comment]
Also - I think I don't have the 4343WA1.BIN file.

wifiupdate

**Comment by jwestmoreland** [comment]
Oh sure - Sebastian - just saw your reply.

I think I don't have the .BIN file...

**Comment by jwestmoreland** [comment]
Well, I've tried to get this to work - it appears to try and download - but when I go back to app development, I still get this:

Please run "PortentaWiFiFirmwareUpdater" sketch once
Please run "PortentaWiFiFirmwareUpdater" sketch once
Please run "PortentaWiFiFirmwareUpdater" sketch once
Please run "PortentaWiFiFirmwareUpdater" sketch once
Please run "PortentaWiFiFirmwareUpdater" sketch once
Please run "PortentaWiFiFirmwareUpdater" sketch once
Please run "PortentaWiFiFirmwareUpdater" sketch once
Please run "PortentaWiFiFirmwareUpdater" sketch once
Please run "PortentaWiFiFirmwareUpdater" sketch once

And it doesn't connect to WiFi.

Regards,
John

**Comment by jwestmoreland** [comment]
Just wondering - in resources.h:

extern const unsigned char wifi_firmware_image_data[416801];

Why doesn't that match what's in the update sketch?

**Comment by facchinm** [comment]
@jwestmoreland we are based on this repo (https://github.com/arduino/mbed-os/blob/portenta_h7/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_PORTENTA_H7/COMPONENT_WHD/resources/firmware/COMPONENT_4343W/resources.h#L24)  so the sizes are consistent :slightly_smiling_face:

**Comment by jwestmoreland** [comment]
Martino,

OK - thanks for that!
John

**Pull request merged**
