### PR TITLE
Make RPC example easier to understand

### PR DESCRIPTION
**Pull request by sebromero**
"Fixes" https://github.com/arduino/ArduinoCore-mbed/issues/96

### CODE REVIEW

**Comment by JSCLadon** [comment]
I am trying to pass a class Value1P from M4 to M7. 
The calass is defined as: 
`class Value1P { 
    int lineID;
    double current;
    double tension;
    Value1P() {
        lineID = 0001;
        current = 0;
        tension = 0;
    };
    ~Value1P() {};
};`
I adjusted the example and got the error message: " Value1P has no member named 'msgpack_unpack' v.msgpack_unpack(o.convert());"

I got stuck. If you improve your examples, could you consider an example, were not only a plain int is passed from one core to another?

That would be just wonderful!

Thanks in advance!

**Comment by facchinm** [comment]
Hi @JSCLadon ,
values being passed from one function to another must be serializable in msgpack (see https://github.com/msgpack/msgpack/blob/master/spec.md#formats for the supported ones). The solution is usually a packer/unpacker from basic types to the actual object before passing it to the function.
@sebromero do you think that adding an example like that would make sense?

**Comment by sebromero** [comment]
@facchinm Yes, I think it would be useful. I would probably put it into a separate sketch but I expect other people to have the same issue.

**Comment by JSCLadon** [comment]
This is a perfect example! Thanks a lot!

**Review by facchinm — APPROVED** [review]

**Pull request merged**
